/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 bags.gltf --transform
Author: alitural (https://sketchfab.com/alitural)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chanel-leather-bag-for-women-76b020e7137b4293b09b66c26091f42f
Title: Chanel Leather Bag for Women
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bags-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.wire_204204204_1} rotation={[-Math.PI / 2, 0, 0]} scale={1.579} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.wire_204204204_2} rotation={[-Math.PI / 2, 0, 0]} scale={1.579} />
    </group>
  )
}

useGLTF.preload('/bags-transformed.glb')
