/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 belt.gltf --transform
Author: Arsutoria - The Workshop School (https://sketchfab.com/arsutoriaschool)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mikaela-jil-sander-belt-49492200b1484a8096671425328ee333
Title: Mikaela - Jil Sander Belt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/belt-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.FABRIC_1_BACK_1459} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.FABRIC_1_FRONT_1459} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.FABRIC_1_SIDE_1459} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material1576} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material196907} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material59949} rotation={[-Math.PI / 2, 0, 0]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/belt-transformed.glb')
