/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 casual.gltf --transform
Author: robotikfoto (https://sketchfab.com/robotikfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shoes-03b951ccfeda447dab552e83041ff831
Title: Shoes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/casual-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.ayakkabi_taba} rotation={[-0.112, 0.677, -2.847]} />
    </group>
  )
}

useGLTF.preload('/casual-transformed.glb')
