/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 formals.gltf --transform
Author: Allay Design (https://sketchfab.com/Alister.Dsouza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cowboy-shoes-9424d591a1324a18945eae010c0bd169
Title: Cowboy -  Shoes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/formal-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.blinn8SG} />
    </group>
  )
}

useGLTF.preload('/formal-transformed.glb')
