/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 handbags.gltf --transform
Author: robotikfoto (https://sketchfab.com/robotikfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/handbag-8f53925a17bb4c30bb6f72994a201c83
Title: Handbag
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/handbags-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Object_5.geometry} material={materials['son_alt.001']} rotation={[-1.55, 0.004, 3.084]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.canta_taban_dolgulu} rotation={[-1.55, 0.004, 3.084]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['son_alt.001']} rotation={[-1.55, 0.004, 3.084]} />
    </group>
  )
}

useGLTF.preload('/handbags-transformed.glb')
