/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 shoe.gltf --transform
Author: Thunk3D scanner (https://sketchfab.com/Diana123456)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shoes-7f3a2e2f36374176beaf41db96b9ac14
Title: Shoes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[0.419, 1.01, 2.494]} />
    </group>
  )
}

useGLTF.preload('/shoe-transformed.glb')
