/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 unknown.gltf --transform
Author: Arsutoria - The Workshop School (https://sketchfab.com/arsutoriaschool)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/marius-klein-3d-shoes-exercises-0d08eae4348345c4bdb40d878ec4d79d
Title: Marius Klein 3d shoes exercises
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/unknown-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['User_1_bianco_base_-_copy_1_0'].geometry} material={materials['bianco_base_-_copy_1']} scale={0.001} />
      <mesh geometry={nodes['Piece_1_millepunte-bianco_0'].geometry} material={materials['millepunte-bianco']} scale={0.001} />
      <mesh geometry={nodes['User_1_2_millepunte-bianco_1_0'].geometry} material={materials['millepunte-bianco_1']} scale={0.001} />
      <mesh geometry={nodes.User_1_3_Gray_0.geometry} material={materials.Gray} scale={0.001} />
      <mesh geometry={nodes.counter1_schlupfriehmen_7_0.geometry} material={materials.schlupfriehmen_7} scale={0.001} />
      <mesh geometry={nodes.User_1_7_Black_0.geometry} material={materials.Black} scale={0.001} />
      <mesh geometry={nodes.qrt_eyestay_LV_0.geometry} material={materials.material} scale={0.001} />
      <mesh geometry={nodes.eylet_vmp_cam_grigio_0.geometry} material={materials.cam_grigio} scale={0.001} />
      <mesh geometry={nodes.oxf_fake_scamo_grigio_0.geometry} material={materials.scamo_grigio} scale={0.001} />
      <mesh geometry={nodes.quarter_upp_Argento_0.geometry} material={materials.Argento} scale={0.001} />
      <mesh geometry={nodes.toe_piece_scamo_grigio_1_0.geometry} material={materials.scamo_grigio_1} scale={0.001} />
      <mesh geometry={nodes.flatlace_Green_0.geometry} material={materials.Green} scale={0.001} />
      <mesh geometry={nodes['Piece_2_bianco_base_-_copy_0'].geometry} material={materials['bianco_base_-_copy']} scale={0.001} />
      <mesh geometry={nodes.counter_overlay_7_schlupfriehmen_7_1_0.geometry} material={materials.schlupfriehmen_7_1} scale={0.001} />
      <mesh geometry={nodes.flatlace_3_Gris_0.geometry} material={materials.Gris} scale={0.001} />
      <mesh geometry={nodes.User_1_9_Workpiece_0.geometry} material={materials.Workpiece} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/unknown-transformed.glb')
