/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 wallet.gltf --transform
Author: Sergey Filin (https://sketchfab.com/sergey.s.filin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-wallet-25a75902f3e5446a893b0de552f42862
Title: Old wallet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/wallet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Default} position={[0, -3.814, 6.716]} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/wallet-transformed.glb')
